image: 'ruby:2.3.3'

services:
  - postgres:latest

variables:
  POSTGRES_DB: rails_template_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

test:
  script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - apt-get install -y nodejs
  - gem install bundler --no-ri --no-rdoc
  - bundle install --path /cache
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake
