image: "ruby:2.3"

test:
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install -j $(nproc) --without production
  - bundle install --path /cache
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake

staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master