Documentation:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 15

CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - config/boot.rb
    - config.ru
  CacheRootDirectory: tmp/
  TargetRubyVersion: 2.3


Rails:
  Enabled: true
